name: All

on:
  push:
  pull_request:

jobs:
  all:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4
      - name: Create user config
        run: |
          cp User.template.xcconfig Config/User.xcconfig
      - name: Source code styling
        run: |
          brew install swiftformat oxfmt
          make style-check
      - name: Linting
        run: |
          brew install swiftlint oxlint
          make lint
      - name: Spell checking
        run: |
          brew install codespell
          make spell-check
      - name: Build
        run: |
          xcodebuild \
              -scheme Moblin \
              -skipPackagePluginValidation \
              build \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO
