name: All

on:
  push:
  pull_request:

jobs:
  all:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Create empty config
        run: |
          touch Config.xcconfig
      - name: Source code styling
        run: |
          brew install swiftformat
          make style-check
      - name: Linting
        run: |
          brew install swiftlint
          make lint
      - name: Build
        run: |
          xcodebuild -list
          xcodebuild -scheme Moblin -skipPackagePluginValidation build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
